Let me follow up on the previous checkin, which may have mended things on mac/clang but broke on other platforms that use gcc! And if some helpful person can send me personal email to set me straight about C++ that might be good. I had code along the lines of the following:
#include <stdio.h>
#include <inttypes.h>

static inline int sample(int32_t a)
{   return a;
}

static inline int sample(int64_t a)
{   return a;
}

int main(int argc, char *argv[])
{   printf("value = %d\n", sample((intptr_t)42));
    return 0;
}

Then gcc "knows" which sort of integer intptr_t is and compiles the code
whihc runs happily (not my code is clearly C rather then C++ at heart, but
lots of CSL still betrays that aspect of its roots). On the Macintosh clang
refuses the ocmpile the code, declaring

g++ overload.cpp -Wall -o overload
overload.cpp:13:28: error: call to 'sample' is ambiguous
{   printf("value = %d\n", sample((intptr_t)42));
                           ^~~~~~
overload.cpp:4:19: note: candidate function
static inline int sample(int32_t a)
                  ^
overload.cpp:8:19: note: candidate function
static inline int sample(int64_t a)
                  ^
1 error generated.

To avoid this I have made a function with a different name just to cope with
the intptr_t case. That feels ugly. At present clang has only complained in
the really small number of places patched here. What other related issues might
be lurking?



git-svn-id: https://svn.code.sf.net/p/reduce-algebra/code/trunk@3992 2bfe0521-f11c-4a00-b80e-6202646ff360